[default]
src = 'contracts'
test = 'test' 
out = 'out'
libs = ['modules']
gas_limit = 9223372036854775807      
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 3
# See more config options https://github.com/gakonst/foundry/tree/master/config
